services:
  jugg-tool-box-service-linux-build:
    image: jugg-tool-box-service-linux-build:latest
    build:
      context: .   # Dockerfile 所在目录
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_bridge_network
    volumes:
      - ./:/app
    # command: /bin/sh -c "cp /app/jugg-tool-box-service /app/build/jugg-tool-box-service"
    # command: /bin/sh -c "go build -o jugg-tool-box-service . && cp /app/jugg-tool-box-service /app/build/jugg-tool-box-service && rm /app/jugg-tool-box-service"
    # command: /bin/sh -c "go build -o jugg-tool-box-service && ./jugg-tool-box-service"
    command: /bin/sh -c "go build -o jugg-tool-box-service"

networks:
  my_bridge_network:
    driver: bridge