appkey: '9SgbBe2ZO/+v4RTHT+yxtmP6HQsJwu8epRt5F6zvhZI='

server:
  port: 8080

database:
  driverName: mysql
  host: mysql
  port: 3306
  database: jugg-tool-box
  username: root
  password: jugg-tool-box-root
  charset: utf8mb4
  timezone: Asia/Shanghai

redis:
  host: redis
  port: 6379
  password: rootroot123

nsqd:
  host: 47.122.55.216
  port: 4150
  
smtp:
  host: smtp.gmail.com
  port: 465
  username: yuyu52905@gmail.com
  password: gtlejquutnkjfiqn
  fromName: JUGG-TOOL-BOX
  fromEmail: yuyu52905@gmail.com

captcha:
  offset: 10 # 允许的拼图偏移量
  puzzleLifeTime: 2 # 单位分
  emailCodeLifeTime: 5 # 单位分

# 图片存储地址 
image:
  maxUserTask: 5
  maxUploadImageSize: 2 # 单位 mb
  upload: images/uploads
  output: images/outputs